### PR TITLE
Separate piped output on press and release 

### PR DESCRIPTION
**Pull request by tmackay**
Added a new command prefix '|' for binding piped output on both keydown and keyup events.
Added output to dump for release bindings

### CODE REVIEW

**Comment by Techjar** [comment]
Looks like you based the PR on the wrong branch; the commits are mess.

**Comment by khampf** [comment]
Me or @tmackay ? :-)
I have little time to review right now so I am afraid i might have messed stuff up by blindly merging...

**Comment by tmackay** [comment]
Just bringing develop up to date with master?

**Comment by khampf** [comment]
I should probably read books on proper conduct on git but develop should be in sync with master, let's do only hotfixes in master in the future - all new functionality in develop or possibly feature-specific branches would probably be better

**Pull request merged**
