### PR TITLE
bring develop up to date with master

### PR DESCRIPTION
**Pull request by tmackay**
include hotfix for profile command and additional error logging for config

### CODE REVIEW

**Comment by tmackay** [comment]
fixes #19 (sort of, depends what you call a mess)

**Comment by khampf** [comment]
Most of the commits (up to commit 1e80eda) are already in develop. I think the result of 039645a is also there as it is you merging my forks master. The bind-keyup-pipe idea I want to give a little thought to before including

**Comment by tmackay** [comment]
Yes, it's only that last hotfix that went into master that's not yet in develop. Probably neater to merge on your side, I was just trying to save you the legwork. I probably did that backwards on my side, but wanted to make sure the previous develop commits got applied after the current state of master.

**Comment by tmackay** [comment]
already merged via more direct path

**Pull request closed without merging**
