### PR TITLE
add additional keybind on release

### LINKED ISSUE #14: feature request for separate bindings on key press and release
One of the things I liked to do in the Logitech Gaming Software was setup LUA scripts to bind multiple actions to a single key. The simplest example is having separate actions on press and release (eg. loot then recast).
In some cases I would insert a timer and perform different actions on release depending on how long the button was held (eg. has GCD passed?).
I have [had a crack at implementing the first case](https://github.com/tmackay/g13/tree/bind-keyup) and TBH I haven't used the second in a long time. If this is something worth including I could submit a pull request.

### PR DESCRIPTION
**Pull request by tmackay**
Also includes previous comment fixes
fixes #14

### CODE REVIEW

**Comment by tmackay** [comment]
also fixes #12

**Comment by Techjar** [comment]
Could you make it work for the other command types as well? Namely pipe output. It's rather limited in usefulness as-is.

**Comment by khampf** [comment]
This really should have been in the dev branch first but I merged into main already - I like the idea but I've had no time to review any of the changes

**Comment by tmackay** [comment]
I'll see if I can extend it out to include piped output, dump and wherever else it occurs. Just finding my way around the code base. Sorry, will PR into develop next time.

**Comment by tmackay** [comment]
> Could you make it work for the other action types as well? Namely pipe output. It's rather limited in usefulness as-is.

Ok, I've worked out how to do it. The question is, what will the bind command look like? For keybinds, whitespace as a delimiter is the obvious choice, but presumably we would want this in the piped text. I'm just not sure how this piped text is going to be used to know if we can just remove certain characters without breaking something. ie.
`bind G1 >Key Pressed<some delimiter>Key Released`

Another option might be to have a separate bind command and event for release eg.
```
bind G1 >Key Pressed
bind G1 <Key Released
```
Although, a multi-character delimiter would be safer, what about '>>'? eg.
`bind G1 >Key Pressed>>Key Released`

**Comment by Techjar** [comment]
Yeah I thought about the delimiter issue. Simultaneous binding seems like it would be fairly complex, as well as requiring an `unbind` command and potentially breaking existing setups, so I don't think that's a good idea. Maybe through `multibind` command or somesuch, but not by changing the behavior of `bind`.

I think a different command prefix for pipe output with both press and release could work to not break any existing setups, though I'm not a fan of `<` because that means pipe in. Maybe `|`, but there's still the question of the delimiter. What about `bind G1 |Key Pressed|Key Released`? We could probably fairly easily support escaping the delimiter like `\|` so the character can still be used literally if needed.

**Pull request merged**
